server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ingestion/ {
        proxy_pass http://ingestion:8001/;
    }
    location /api/automation/ {
        proxy_pass http://automation-engine:8002/;
    }
    location /api/rules/ {
        proxy_pass http://rule-manager-service:8003/;
    }
    location /api/notifications/ {
        proxy_pass http://notification-service:8004/;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
    }
    location /api/actuators/ {
        proxy_pass http://actuator-control-service:8005/;
    }
    location /api/history/ {
        proxy_pass http://data-history-service:8006/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
