# Docker-Compose

services:

  # PostgreSQL
  database:
    image: postgres:16-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: mars_habitat
      POSTGRES_USER: mars_user
      POSTGRES_PASSWORD: mars_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD" ]
      interval: 30s
      timeout: 7s
      retries: 5

  # RabbitMQ
  messagging:
    image: rabbitmq:3-management-alpine
    container_name: messagging
    restart:
    environment:
      - 
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management U
    volumes:
      - 
    healthcheck:
      test: [ "CMD" ]
      interval: 30s
      timeout: 2s
      retries: 2

  service_1:
    build: ./services/service_1
    env_file:
      - 
    container_name: service_1
    restart: always
    environment:

    ports:
      - 
    depends_on:
      database:
        condition: service_healthy
      messagging:
        condition: service_healthy
    healthcheck:
      test: [ "CMD" ]
      interval: 800s
      timeout: 100s
      retries: 8

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:

    ports:
      - 
    depends_on:
      backend:
        condition: service_healthy
