# Docker-Compose

services:
  # PostgreSQL
  database:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: mars_habitat
      POSTGRES_USER: mars_user
      POSTGRES_PASSWORD: mars_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mars_user -d mars_habitat" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ
  messagging:
    image: rabbitmq:3-management
    container_name: messagging
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: mars_user
      RABBITMQ_DEFAULT_PASS: mars_password
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  ingestion:
    build: ./ingestion
    container_name: ingestion
    restart: always
    environment:
      SIMULATOR_URL: http://host.docker.internal:8080
      RABBITMQ_URL: amqp://mars_user:mars_password@messagging:5672/
      EXCHANGE_NAME: mars_events
      POLL_INTERVAL: 10
      HOST: 0.0.0.0
      PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      messagging:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  automation-engine:
    build: ./automation-engine
    container_name: automation-engine
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://mars_user:mars_password@database:5432/mars_habitat
      RABBITMQ_URL: amqp://mars_user:mars_password@messagging:5672/
      EXCHANGE_NAME: mars_events
      ROUTING_KEY: events.sensor.#
      RULES_RELOAD_INTERVAL: 30
      HOST: 0.0.0.0
      PORT: 8002
    ports:
      - "8002:8002"
    depends_on:
      database:
        condition: service_healthy
      messagging:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8002/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  actuator-control-service:
    build: ./actuator-control-service
    container_name: actuator-control-service
    restart: always
    environment:
      SIMULATOR_URL: http://host.docker.internal:8080
      DATABASE_URL: postgresql+asyncpg://mars_user:mars_password@database:5432/mars_habitat
      RABBITMQ_URL: amqp://mars_user:mars_password@messagging:5672/
      EXCHANGE_NAME: mars_events
      COMMAND_ROUTING_KEY: commands.actuator.#
      HOST: 0.0.0.0
      PORT: 8005
    ports:
      - "8005:8005"
    depends_on:
      database:
        condition: service_healthy
      messagging:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8005/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    environment:
      RABBITMQ_URL: amqp://mars_user:mars_password@messagging:5672/
      EXCHANGE_NAME: mars_events
      ROUTING_KEY: events.#
      HOST: 0.0.0.0
      PORT: 8004
    ports:
      - "8004:8004"
    depends_on:
      messagging:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8004/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  data-history-service:
    build: ./data-history-service
    container_name: data-history-service
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://mars_user:mars_password@database:5432/mars_habitat
      RABBITMQ_URL: amqp://mars_user:mars_password@messagging:5672/
      EXCHANGE_NAME: mars_events
      ROUTING_KEY: events.sensor.#
      HOST: 0.0.0.0
      PORT: 8006
    ports:
      - "8006:8006"
    depends_on:
      database:
        condition: service_healthy
      messagging:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8006/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  rule-manager-service:
    build: ./rule-manager-service
    container_name: rule-manager-service
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://mars_user:mars_password@database:5432/mars_habitat
      HOST: 0.0.0.0
      PORT: 8003
    ports:
      - "8003:8003"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8003/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      automation-engine:
        condition: service_healthy
      ingestion:
        condition: service_healthy
      actuator-control-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
      data-history-service:
        condition: service_healthy
      rule-manager-service:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data:
